version: '3.12'

services:
  db:
    image: postgres:16
    restart: always
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    restart: always
    container_name: fastapi_app
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]

volumes:
  postgres_data:
