version: '3.12'

services:
  db:
    image: postgres:16
    restart: always
    container_name: postgres_db
    env_file:
      - .env
    environment:
      POSTGRES_DB: SecGaOneC2
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 5s
      retries: 5

  app:
    build: .
    restart: always
    container_name: fastapi_app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: [ "poetry", "run", "uvicorn", "api.app:app", "--host", "0.0.0.0", "--port", "8000" ]

volumes:
  postgres_data:
